### ISSUE TITLE
not support language arabic

### ISSUE THREAD

**Issue by SyrianProgrammer** [HardFork/KeepToText#3]

**Comment by dan-and** [comment]
It will be pretty easy includeable in my patch for the german language. 

See: https://github.com/HardFork/KeepToText/pull/1

**Comment by HardFork** [comment]
I merged the pull request by dan-and for German.  Please give me some test data for Arabic and I will try to add that.  Please comment here and attach a Google Keep zip file with your test data.

**Comment by HardFork** [comment]
I added Unicode decoding calls which will help with Arabic.  I still need to know the name of the Keep folder in Arabic.  Closing this now.  Open a new one if you can give me the Arabic folder name.

**Comment by HardFork** [comment]
I just made an update that will search for the correct directory without having to know a translated name.  Please test it in German and Arabic and let me know.

**Comment by HardFork** [comment]
Please get the latest version of the script and try with Arabic
