### ISSUE TITLE
Doesn't transfer Google Keep labels

### ISSUE THREAD

**Issue by skayser** [HardFork/KeepToText#4]
I just came across this script. When I run it on the Google Takeout ZIP the result is a folder full of text files containing the notes from Google Keep, but without any of the associated labels. Is there any chance to include the labels in a way that the Evernote import process understands?

**Comment by skayser** [comment]
I've switched from Evernote to CintaNotes and made some changes to your script so that it produces output that can be imported to CintaNotes. The modified script also supports labels. Maybe you can take away some ideas. Mainly, I've changed the HTML parsing/extraction from HTMLparser to lxml with XPath support.

I've pasted it as a Gist. https://gist.github.com/skayser/1eccc65ce50afd16f406f383e80b6cf6

It's not polished by any means, but it works for me for now.

**Comment by HardFork** [comment]
I committed your gist as fd74907e316b7ef695c79220585343cdc6227d59 (specifying you as author).  I merged it into master and added a --format option to specify either Evernote (the default) or CintaNotes.  (See the ReadMe)
