### ISSUE TITLE
Detect platform-specific file encoding instead of defaulting to utf-8?

### ISSUE THREAD

**Issue by skayser** [HardFork/KeepToText#5]
I am sitting on a german Windows 10 installation. On this system, the Evernote importer expects files to be encoded with cp1252 instead of the utf-8 default that's used by this script. Thus, after the import, the german umlauts in the notes end up garbled.

Even though this might be an issue on the Evernote side, I just wanted to let people know that they can work around this in the meantime by changing the encoding of the output files to cp1252 (instead of utf-8).

Just change this:

`    with codecs.open(inputPath, "r", "utf-8") as inf, codecs.open(outfname, "w", "utf-8") as outf:`

to this:

`    with codecs.open(inputPath, "r", "utf-8") as inf, codecs.open(outfname, "w", "cp1252") as outf:`

Maybe this script could detect the "proper" platform encoding instead of defaulting to utf-8?

**Comment by skayser** [comment]
Just to make things more complicated. I've dabbled with various note-keeping apps on the receiving end. One of them is Boostnote. It can also import text files, but this time, it expects the encoding to be UTF-8, i.e. when being fed with CP1252 encoded textfiles the umlauts are garbled. So there doesn't seem to be a one-size-fits-all solution when using different note-keeping apps.

**Comment by HardFork** [comment]
I added the --encoding and --system-encoding options in e396ce85091f6dfa5e9ae3010420fe5116f1d1c4
